### ISSUE TITLE
Changes in Ddm.Manifest.xml

### ISSUE THREAD

**Issue by EleonoraPetzold** [bexis/Module_LUI#11]
To call the function "SchowPrimaryData" a added that function to internalAPI in DDM manifest file. We need to speak with David maybe we can add it in core, too. Or this is a change in our core and we need to care about it.

**Comment by geofranzi** [comment]
I think we can ..this should have no bad impact

**Comment by EleonoraPetzold** [comment]
is in out core. We can close this issue.
