### ISSUE TITLE
Review page if dataset selection changes

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_LUI#12]
If I switch between OLD and NEW component (and have chosen unstandardized) already the result page is not reseted and I see still the formerly chosen set.

![image](https://user-images.githubusercontent.com/26480843/84394832-baf64a00-abfd-11ea-992b-57803bf774f3.png)

**Comment by EleonoraPetzold** [comment]
> If I switch between OLD and NEW component (and have chosen unstandardized) already the result page is not reseted and I see still the formerly chosen set.
> 
> ![image](https://user-images.githubusercontent.com/26480843/84394832-baf64a00-abfd-11ea-992b-57803bf774f3.png)

Die standardized selection verschwindet, wird also resetet aber es ist richtig der result view sollte dann auch wider verschinden.

**Comment by EleonoraPetzold** [comment]
fixed.
