### ISSUE TITLE
Remove update/append button in lui tool for unstandardized data view

### ISSUE THREAD

**Issue by EleonoraPetzold** [bexis/Module_LUI#16]
![image](https://user-images.githubusercontent.com/42029171/86894220-10415080-c103-11ea-8458-0988818de64f.png)

**Comment by EleonoraPetzold** [comment]
@franzi, das wird schwierig, oder?  Aber an der Stelle ist  eine upload option das sehr unpassend.
@aostrow, was sagst du?

**Comment by aostrow** [comment]
Upload wäre ja in einen der input-Datensätze. Den Workflow kennen die Leute, die das anbieten eigentlich. 
Hier müsste man ja
- bei dem Button die Rechte abfangen, wer uploaden darf (geht das schon?) und
- dann wäre noch die Frage welcher der beiden Datensätze genommen wird (wohl der aktuellere). 

Höchstens statisch auf Upload eines Datensatzes verlinken, wenn man Rechte hat. Ist aber von geringer Priorität.

**Comment by EleonoraPetzold** [comment]
> * dann wäre noch die Frage welcher der beiden Datensätze genommen wird (wohl der aktuellere).

Der der ausgewählt wurde. Also old order new set. Der view hier kommt aus B2 und läd einfach die Primärdaten eines Datensatzes je nach ID.

**Comment by EleonoraPetzold** [comment]
> * bei dem Button die Rechte abfangen, wer uploaden darf (geht das schon?) und

Das habe ich gar nicht geprüft. ich habe gerade die vollen Rechte. ich schau mir das mal mit nur "view" Rechten an.

**Comment by EleonoraPetzold** [comment]
Wenn ich nur "view" Rechte habe sehe ich den button nicht. Das funktioniert! D.h. es sehen zb nur die LMT hier den upload button. Das ist nicht schön aber wahrscheinlich können wir das so lassen.Was denkt ihr?

**Comment by aostrow** [comment]
Ähm, eigentlich hat jeder view-Rechte und sonst niemand irgendwas Besonderes, Höchstens halt Rechte auf den unterliegneden Datensätzen, da Owner. Oder?

**Comment by EleonoraPetzold** [comment]
Ja es geht hier um die beiden darunter liegenden Datensätze. Wenn unstandardized gewählt wird der normale Primary Data view von B2 geladen. Wenn man also mehr als "view" rechte auf einen der beiden Datensätze hat sieht man den button.

**Comment by aostrow** [comment]
Ok, dann sehen den "nur" die Owner. Das ist ok.

**Comment by EleonoraPetzold** [comment]
jupp, ok dann schließe ich das issues :)
