### ISSUE TITLE
Improve readability for download buttons

### ISSUE THREAD

**Issue by geofranzi** [bexis/Module_LUI#18]
currently not easy to read
- [ ] replace "download" by icon

**Comment by EleonoraPetzold** [comment]
in b1:
![image](https://user-images.githubusercontent.com/42029171/87274630-7bf93400-c4dc-11ea-86a4-bcd561412239.png)

auch nicht so schön aber besser zu lesen. Icon setzt ich bei B2 rein.

**Comment by EleonoraPetzold** [comment]
Das ActionLinks mit der Klasse bx-button small. Keine Ahnung wir ich nur einem Teil des Link text eine andere css Klasse geben soll. @geofranzi hast du ne Idee?

` @Html.ActionLink("How To", "DownloadPDF", new { fileName = "HowToLUI.pdf" }, new { @class = "bx-button small function", target = "_blank" })
`

Ich hab erst mal das "Download" weg gemacht. Damit ist die Lesbarkeit auch schon besser.

**Comment by EleonoraPetzold** [comment]
> Das ActionLinks mit der Klasse bx-button small. Keine Ahnung wir ich nur einem Teil des Link text eine andere css Klasse geben soll. @geofranzi hast du ne Idee?

@geofranzi hattest du meine Frage gesehen?

**Comment by geofranzi** [comment]
Das einfachste ist wahrscheinlich einfach gleich das finale HTML zu schreiben.

**Comment by EleonoraPetzold** [comment]
die Buttons sind jetzt wie in B1 un so mit den LMTs abgesprochen .... siehe #27
