### ISSUE TITLE
 OldSet  NewSet

### ISSUE THREAD

**Issue by geofranzi** [bexis/Module_LUI#19]
- [ ] check / change writing (old set / new set)
- [ ] necessary to write "set" instead of e.g. old (from year x to year y) / new (from 2019)?

**Comment by aostrow** [comment]
? verstehe nicht ganz die tasks, auf jeden Fall sind die drunterliegenden Datensätze (data sets) unterschiedlich, da die Berechnung verändert/angepasst wurde.
Das heißt, das neue Set deckt auch die gleichen Jahre ab, wie das alte Set + natürlich, dass die neuen Jahre nun hier hinzu kommen.

**Comment by geofranzi** [comment]
Ok, na ich wusste nicht was sich zwischen "alt" und "neu" geändert hat. Aber vielleicht gibt ja trotzdem eine Zeit, wo das geändert wurde. Bei der Schreibweise geht es darum, dass "OldSet" so erstmal kein Name ist. Das sieht halt mehr die wie die Variable ausm Code aus ;-) 
Vielleicht dann sowas wie:
"Which input data do you want to use? Old is based on the previous (until 2016) method to calculate the base dataset.
- Old  (until 2016)  / new

**Comment by aostrow** [comment]
- Old (until 2016) geht nicht, da die Leute dann denken, da sind die Daten bis 2016 drin und in new dann ab 2017.
- in B1 heißt das auch "old components set" und nicht nur "old set". Kann das nicht so bleiben? Was ist das Problem?
![image](https://user-images.githubusercontent.com/26480843/87280886-f16fff00-c4f2-11ea-8bee-9cec214e0f59.png)

**Comment by EleonoraPetzold** [comment]
der LUI tool ist so geschrieben das der Wert der angezeigt wird gleichzeitig der Wert ist mit dem man arbeitet. Die Werte werden im Model gesetzt:
`ComponentsSet.Values = new List<string>() { "OldSet", "NewSet" };`
 Ich denke das machen die Leerzeichen Probleme.  Ich kann es aber mal probieren mit "old components set" oder alterativ "OldComponentsSet"?

Wenn die alterative blöd ist muss ich den tool an der Stelle umschreiben ... keine Ahnung wie lange das dauert. Vlt ist es gar nicht viel. ich kann es gerade nicht einschätzen.

**Comment by aostrow** [comment]
Oder, wie Franzi sagt, einfach Old / New und fertig.

**Comment by EleonoraPetzold** [comment]
Mit Leerzeichen scheint zu gehen :) Sorry hätte ich auch früher ausprobieren können ...
