### ISSUE TITLE
Error shown on old+unstandardized

### ISSUE THREAD

**Issue by geofranzi** [bexis/Module_LUI#21]
![image](https://user-images.githubusercontent.com/15946467/87251974-eaec7380-c46f-11ea-949f-b1b0b2ea0224.png)

**Comment by geofranzi** [comment]
related test: https://github.com/SirkoS/BexisTest/commit/2c8093e1bee2066c2cfae2a55c7196fe5d4b87fe

**Comment by EleonoraPetzold** [comment]
Du hast keine rechte auf den Datensatz! Eine andere Fehlermeldung wäre schön aber der teil wird aus B2 geladen ....
