### ISSUE TITLE
Rights on lui datasets

### ISSUE THREAD

**Issue by EleonoraPetzold** [bexis/Module_LUI#23]
Wir machen wir das mit den Datensätzen? Wollen wir eine Gruppe LUI erstellen die Rechte drauf hat und jeder User bekommt die? Oder die Rechte an eine bestehende Gruppe die jeder an?

**Comment by aostrow** [comment]
Von mir aus kann man die eigentlich an die Rolle/Gruppe "centralData" hängen. Wären die ja. Oder?

**Comment by EleonoraPetzold** [comment]
Die beiden LUI sind ja schon in "centralData", oder? Jedenfalls haben ganz viele user view rechte in B1. Aber in B2 sind die Rechte nicht da.

**Comment by aostrow** [comment]
Ja, die sind beide schon in centralData drin. Hm, Mist.

**Comment by EleonoraPetzold** [comment]
Ok muss ich prüfen, was da los ist.

**Comment by EleonoraPetzold** [comment]
lui ist in central data und beim lokalen test sind sie rechte richtig gesetzt. Das muss noch mal beim nächsten Run auf dem server geprüft werden.

**Comment by EleonoraPetzold** [comment]
jetzt passt es und central data hat view rechte auf die LUI Datensätze
