### ISSUE TITLE
Correct? Same settings B1 & B2 different results

### ISSUE THREAD

**Issue by geofranzi** [bexis/Module_LUI#26]
![image](https://user-images.githubusercontent.com/15946467/87685832-1fb83d80-c784-11ea-9009-c17231086620.png)

![image](https://user-images.githubusercontent.com/15946467/87685904-2fd01d00-c784-11ea-9a0a-5bfbe80ceaa4.png)

**Comment by aostrow** [comment]
At first, we schould check the underlying datasets (unstructured view). Is the migrated data the same?

**Comment by aostrow** [comment]
In B2 the Year column seems to have weird entries (1/1/2012)

**Comment by geofranzi** [comment]
> In B2 the Year column seems to have weird entries (1/1/2012)

wo sieht man das?

**Comment by geofranzi** [comment]
Calculation fix, display not.
