### ISSUE TITLE
Adapt pdf download to B1

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_LUI#27]
in Bexis1 the donwload buttons + pdfs have changed, need to be adapted

![image](https://user-images.githubusercontent.com/26480843/87789386-412a2f80-c83f-11ea-9ebd-52096064a9f2.png)

[LUI-citation.pdf](https://github.com/bexis/Module_LUI/files/4937987/LUI-citation.pdf)
[HowToPlusDiagram.pdf](https://github.com/bexis/Module_LUI/files/4937986/HowToPlusDiagram.pdf)
[LuiChangesInfo.pdf](https://github.com/bexis/Module_LUI/files/4937985/LuiChangesInfo.pdf)

**Comment by EleonoraPetzold** [comment]
done
