### ISSUE TITLE
Notification about LUI component data for LUI calculation 

### ISSUE THREAD

**Issue by EleonoraPetzold** [bexis/Module_LUI#35]
Add notification box above the calculation form and show there all years where component data is missing.  That means when plots per year and explo < 50. 
Add information which plots are missing, too. 
Which plots are missing should be visible through open and close caps.

**Comment by aostrow** [comment]
Text draft:
Warning: Some input data needed for calculation is not completely available. Below you will find the affected years, and for which plots the data is missing. For this year, use the LUI just for testing purposes. For publications, use only LUI where no warning is given.
