### ISSUE TITLE
Find C# equivalent  for R predict 

### ISSUE THREAD

**Issue by EleonoraPetzold** [bexis/Module_LUI#38]
R code line 82:
`Pred <- predict(lm(Slurry ~ Time, data = Dat), newdata = data.frame(Time = 3))`

**Comment by aostrow** [comment]
explains what R is doing: https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/predict.lm

maybe this is of interest: 
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/predict-prices
https://stackoverflow.com/questions/1557507/what-is-a-good-statistical-math-package-for-net
https://medium.datadriveninvestor.com/5-open-source-math-libraries-78d856f4733c

**Comment by aostrow** [comment]
google for: interpolate linear model  c#

**Comment by EleonoraPetzold** [comment]
we don't need this at this moment, there are too few cases for that Interpolation
