### ISSUE TITLE
Need public version without using the non-full available year

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_LUI#53]
We are working on a new version where the data is also used if not the whole year of raw data is available. But this should work only internally. 
We want to make the LUI tool public. Therefore we need a solution if non-full raw data exists.

**Comment by EleonoraPetzold** [comment]
Check if the user accessing it has an account. If not, it is a public access and the not complete years are not taken into account.

**Comment by EleonoraPetzold** [comment]
@ please test the new feature on 2010
