### ISSUE TITLE
Add percentage info to the warning-box

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_LUI#55]
Add to the warning box data about available data of the plots:
ALB: xxx %
HAI: xxx %
SCH: xxx %

Suggestion:
![image](https://user-images.githubusercontent.com/26480843/185405933-56bf63d0-d4bc-4eb7-b93b-1a42f8d4d2ba.png)

**Comment by aostrow** [comment]
HAI says 110% which is suspicious

**Comment by EleonoraPetzold** [comment]
Reason: duplicates in data
