### ISSUE TITLE
Re-order years in selection-box

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_LUI#62]
Would be nice to have the years nicely ordered.

![grafik](https://user-images.githubusercontent.com/26480843/221546465-ce9b70fb-2fe5-469e-abd6-0f2f63cf4d33.png)

In BExIS(1) we used some kind of UI element which did it automatically. Is this possible here too?

<asp:CheckBoxList ID="CheckBoxList_Years" runat="server" RepeatDirection="Horizontal" RepeatColumns="4" CellSpacing="5">

**Comment by EleonoraPetzold** [comment]
For me it looks ok:
![image](https://user-images.githubusercontent.com/42029171/223354145-da03b914-ec34-4c5b-892b-f4bf6e1ee4c8.png)

which browser do you use?

**Comment by aostrow** [comment]
firefox

first element
![grafik](https://user-images.githubusercontent.com/26480843/223357016-796210a3-01ec-4db9-9f67-17da441a47db.png)

element with line break
![grafik](https://user-images.githubusercontent.com/26480843/223357147-16fd613a-7441-4bb8-a475-33db5b043b11.png)

**Comment by aostrow** [comment]
Franzi re-ordered elemenst in seach facet pop-up. Maybe this is helpful?
https://github.com/bexis/BExIS-intern/issues/540

**Comment by EleonoraPetzold** [comment]
fixed and published on prod and dev
