### ISSUE TITLE
Introduce new components set in LUI tool 

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_LUI#78]
Errors in the calculation of the LUI components were discovered and are corrected (soon) #77 . Afterwards, we need the option to (default) select the new components set in the LUI tool.

New dataset is: 31661

Draft for UI: 
![UySp07TWeReBxYVV](https://github.com/bexis/Module_LUI/assets/26480843/eda7c8d1-40da-417c-b54f-59f37e0cfe1a)

maybe better to write: historic set till 2019 ...

**Comment by aostrow** [comment]
It is published on the production server. 
@EleonoraPetzold: do you commit the code and close the issue?

**Comment by EleonoraPetzold** [comment]
Is committed
