### ISSUE TITLE
Add missing years

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_LUI#9]
- missing years > 2016; in B1 we have

aspx file:
`<asp:ListItem Text="2017 (new set only)" Value="2017" />
<asp:ListItem Text="2018 (new set only)" Value="2018" />`

c# file (result):
`if (this.RadioButtonList0_ComponentSet.SelectedValue == "19266")
{
    selectedYearList.Remove("2017");
    selectedYearList.Remove("2018");
} `

**Comment by EleonoraPetzold** [comment]
![image](https://user-images.githubusercontent.com/42029171/84887740-83bce880-b096-11ea-8dac-2eb3b42970c4.png)

Habs jetzt so gemacht. Bist du einverstanden? Können wir das issue schließen?

**Comment by aostrow** [comment]
Ok, sieht gut aus.
